In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
arr = np.array([ [0,1],[2,3],[4,5] ])
print(arr)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
l = arr.tolist()

In [4]:
print(l)

[[0, 1], [2, 3], [4, 5]]


In [6]:
arr1 = np.array([0,1,2])
arr2 = np.array([2,1,0])
data = np.array([arr1,arr2])
covMatrix = np.cov(data,bias=True)
print(arr1)
print(arr2)
print(data)
print(covMatrix)

[0 1 2]
[2 1 0]
[[0 1 2]
 [2 1 0]]
[[ 0.66666667 -0.66666667]
 [-0.66666667  0.66666667]]


In [11]:
import math
D = [100, 150, 180]
def prog(D):
    L = []
    H= 30
    C = 50
    for d in list:
        L.append(math.floor(math.sqrt((2*C*d)/H)))
    return L
print(prog(D))


[18, 22, 24]
